---
name: Gradle

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  build:
    strategy:
      matrix:
        java: [8, 11, 17]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    env:
      gradle_commands: --stacktrace build
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: 'zulu'
      - name: Install libraries
        run: |
          sudo apt-get install -y libblosc1
      - name: Run commands
        run: |
          ./gradlew ${{ env.gradle_commands }}
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: raw2ometiff ${{ matrix.java }}
          path: build/distributions/*.zip
          retention-days: 30
